### ISSUE TITLE
Link invalidi

### ISSUE THREAD

**Issue by angelogulina** [AgID/lg-domiciliodigitalecittadino-docs#1]
Per il file https://github.com/AgID/lg-domiciliodigitalecittadino-docs/blob/077540302d2beed045b3af67d014b9727d709566/istruzioni_consultazione.rst i link alle sezioni `Docs Italia` e `Forum Italia` sono invalidi.

Rispettivamente: http://xxxxxxx/ e https://forum.italia.it/c/documenti-in-consultazione/XXXXXXX)/).

**Comment by vintra73** [comment]
La ringrazio per la segnalazione. Provvediamo a fixare il bug.
