### ISSUE TITLE
https://forum.italia.it/t/domicilio-digitale/2345/45

### ISSUE THREAD

**Issue by AndreaTironi1** [AgID/lg-domiciliodigitalecittadino-docs#4]
Bene, finalmente. Ammetto che non mi convince che il domicilio digitale dei privati sia ancora un indirizzo PEC soggetto alle bizze degli interessati in quanto a abbonamento/rinnovo e correlativa registrazione/variazione/cessazione in INAD (avrei preferito una piattaforma centralizzata con area riservata, anche per la conservazione degli atti nel tempo da parte del destinatario), non mi convince che sia l’interessato a registrarlo presso l’INAD (avrei preferito fosse mediata dal Comune di residenza), non mi convince che il soggetto iscritto in INIPEC (imprenditore/professionista) possa registrare come privato un domicilio digitale diverso da quello in INIPEC (non è chiaro l’ambito d’uso di uno o dell’altro in casi borderline da parte di chi deve notificare atti).

https://forum.italia.it/t/domicilio-digitale/2345/45

Non sono miei ma alcuni sono interessanti.

**Comment by vintra73** [comment]
Buongiorno, la invito a fare commenti sul Forum.

Nello specifico https://forum.italia.it/c/documenti-in-consultazione/linee-guida-domicilio-digitale
