### ISSUE TITLE
IBAN

### ISSUE THREAD

**Issue by AndreaTironi1** [AgID/lg-domiciliodigitalecittadino-docs#5]
Al domicilio digitale non si potrebbe aggiungere anche un iban,
in modo che in futuro se dovessero essere dati dei soldi al cittadino
si sa già come inviarli?

Andrea

**Comment by vintra73** [comment]
Buongiorno, la invito a fare commenti sul Forum.

Nello specifico https://forum.italia.it/c/documenti-in-consultazione/linee-guida-domicilio-digitale
